package se.citerus.dddsample.domain.model.cargo;

import lombok.EqualsAndHashCode;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import se.citerus.dddsample.domain.shared.ValueObject;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the application.
 *  
 */
@EqualsAndHashCode
@RequiredArgsConstructor
public final class TrackingId implements ValueObject<TrackingId> {

  @NonNull
  private String id;

  /**
   * @return String representation of this tracking id.
   */
  public String idString() {
    return id;
  }

  @Override
  public String toString() {
    return id;
  }

  TrackingId() {
    // Needed by Hibernate
  }
}
